apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: grupo1
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - name: metrics-backend
      port: 8000
      targetPort: 8000
      protocol: TCP
      nodePort: 30071
# Service para expor o backend dentro do cluster
# Porta 8001 para comunicação interna