apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: grupo1
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8001
      targetPort: 8001
# Service para expor o backend dentro do cluster
# Porta 8001 para comunicação interna