apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: grupo1-backend-podmonitor
  namespace: grupo1
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  podMetricsEndpoints:
    - port: metrics-backend
      path: /metrics
      interval: 15s
