apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trail-run-app
  namespace: grupo1
spec:
  project: grupo1
  source:
    repoURL: "https://github.com/VitorRemesso2050519/projeto-sd-grupo-1"
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: grupo1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
