apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector: { app: trail-backend }
  ports:
  - port: {{ .Values.backend.port }}
    targetPort: {{ .Values.backend.port }}