apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.serviceName }}
  #namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector: { app: trail-frontend }
  ports:
  - port: 80
    targetPort: {{ .Values.frontend.port }}