apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  username: {{ .Values.rabbitmq.username | quote }}
  password: {{ .Values.rabbitmq.password | quote }}