apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: grupo1
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: vitorremesso/frontend:8ef3692
          ports:
            - containerPort: 81
          readinessProbe:
            httpGet:
              path: /
              port: 81
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /
              port: 81
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          volumeMounts:
            - name: gpx-volume
              mountPath: /usr/share/nginx/html/gpx
      volumes:
        - name: gpx-volume
          persistentVolumeClaim:
            claimName: pvc-gpx
# Deployment do serviço frontend
# Utiliza readiness e liveness probes para garantir disponibilidade
# Volume para ficheiro GPX via PVC
# Limites de recursos definidos.