apiVersion: v1
kind: Pod
metadata:
  name: gpx-loader
  namespace: trail-run
spec:
  restartPolicy: Never
  containers:
    - name: loader
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: gpx-volume
          mountPath: /data
  volumes:
    - name: gpx-volume
      persistentVolumeClaim:
        claimName: gpx-pvc