apiVersion: v1
kind: ConfigMap
metadata:
  name: simulator-config
data:
  SIM_DEBUG: "0"
  GPX_FOLDER: "/app/gpx-files"
  RABBIT_EXCHANGE: "events"
  RABBIT_ROUTING_KEY: "gps.update"
  SIM_PUBLISH_INTERVAL: "1" # Intervalo entre as mensagens de localização dos atletas em segundos
  SIM_NUM_ATHLETES: "15"  # Número de atletas simulados por corrida
  # --- Variáveis de performance e logging ---
  SIM_POOL_SIZE: "10"           # Tamanho do pool de conexões/canais RabbitMQ
  SIM_LOG_LEVEL: "WARNING"        # Nível de logging: DEBUG, INFO, WARNING, ERROR
