apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grupo1-backend-monitor
  labels:
    release: kube-prometheus-stack
    namespace: monitoring
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - grupo1
  endpoints:
    - port: metrics-backend
      path: /metrics
      interval: 15s
    