apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: simulator-monitor
  labels:
    release: kube-prometheus-stack
    namespace: monitoring
spec:
  selector:
    matchLabels:
      app: simulator
  namespaceSelector:
    matchNames:
      - grupo1
  endpoints:
    - port: metrics-simulator
      path: /metrics
      interval: 15s