apiVersion: v1
kind: Service
metadata:
  name: simulator-metrics
  namespace: grupo1
  labels:
    app: simulator
spec:
  selector:
    app: simulator
  ports:
    - name: metrics-frontend
      port: 8080
      targetPort: 8080