apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
  namespace: grupo1
  labels:
    app: simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
        - name: simulator
          image: vitorremesso/simulator:4508d3b
          ports:
            - containerPort: 8080
              name: metrics-sim
          env:
            - name: RABBIT_USER
              valueFrom: 
                secretKeyRef:
                  name: rabbitmq-auth
                  key: username
            - name: RABBIT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-auth
                  key: password
            - name: RABBIT_URL
              value: amqp://$(RABBIT_USER):$(RABBIT_PASS)@rabbitmq-cluster.rabbitmq-system.svc.cluster.local:5672/
            - name: RABBIT_EXCHANGE
              valueFrom:
                configMapKeyRef:
                  name: simulator-config
                  key: RABBIT_EXCHANGE
            - name: RABBIT_ROUTING_KEY
              valueFrom:
                configMapKeyRef:
                  name: simulator-config
                  key: RABBIT_ROUTING_KEY
            - name: GPX_FOLDER
              valueFrom:
                configMapKeyRef:
                  name: simulator-config
                  key: GPX_FOLDER
            - name: SIM_PUBLISH_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: simulator-config
                  key: SIM_PUBLISH_INTERVAL
            - name: SIM_NUM_ATHLETES
              valueFrom:
                configMapKeyRef:
                  name: simulator-config
                  key: SIM_NUM_ATHLETES
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
          volumeMounts:
            - name: gpx-volume
              mountPath: /app/gpx-files
      volumes:
        - name: gpx-volume
          persistentVolumeClaim:
            claimName: pvc-gpx
# Deployment do simulador de atletas
# Utiliza variáveis de ambiente seguras via Secret
# Volume para ficheiro GPX via PVC
# Limites de recursos e probes definidos
