apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: simulator-podmonitor
  namespace: grupo1
  labels:
    app: simulator
spec:
  selector:
    matchLabels:
      app: simulator
  podMetricsEndpoints:
    - port: metrics-simulator
      path: /metrics
      interval: 15s
