apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: grupo1-simulator-podmonitor
  namespace: grupo1
  labels:
    app: simulator
spec:
  selector:
    matchLabels:
      app: simulator
  podMetricsEndpoints:
    - port: metrics-sim
      path: /metrics
      interval: 15s
